import { Scene } from "@/types/game";

export const ACT_1_SCENES: Scene[] = [
  {
    id: "act1_s1",
    type: "transition",
    act: 1, sceneNumber: 1,
    text: "4th November.\nPagi yang seperti biasa...",
    bg: { color: "#06020f" },
    duration: 3200,
    next: "act1_s2",
    audio: { bgm: "/audio/bgm/act_1.mp3" }, // ← BGM starts here; persists through all scenes that don't change it
  },
  {
    id: "act1_s2",
    type: "monologue",
    act: 1, sceneNumber: 2,
    text: "Aku membuka mata.\n\nSemuanya terasa... biasa. Seperti hari-hari lainnya.",
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act1_s3",
    // No audio field → AudioManager keeps playing act_1.mp3 (correct behaviour)
  },
  {
    id: "act1_s3",
    type: "dialogue",
    act: 1, sceneNumber: 3,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "Ohayo~! Kamu akhirnya bangun juga.",
    characters: [{
      id: "rinn",
      sprite: "/Image/Rinn/eye-close-smile.png",
      position: "right",
      size: "large",
      animation: "enter-bottom",
    }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act1_s4",
    // ── Voice line is now enabled ──────────────────────────────────────────
    // Make sure the file exists at: /public/audio/voice/act_1/act1_s3.mp3
    audio: { voice: "/audio/voice/act_1/act1_s3.mp3" },
  },
  {
    id: "act1_s4",
    type: "monologue",
    act: 1, sceneNumber: 4,
    text: "Gadis itu berdiri di depanku, tersenyum seperti tidak ada yang aneh.\n\nTapi... siapa dia?",
    characters: [{
      id: "rinn",
      sprite: "/Image/Rinn/eye-close-smile.png",
      position: "right",
      size: "large",
      dim: true,
    }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act1_s5",
  },
  {
    id: "act1_s5",
    type: "dialogue",
    act: 1, sceneNumber: 5,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "Aku Rinn. Masa kamu lupa? Kita sudah kenal sejak lama, lho.",
    characters: [{
      id: "rinn",
      sprite: "/Image/Rinn/eye-close-smile.png",
      position: "right",
      size: "large",
    }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act1_s6",
  },
  {
    id: "act1_s6",
    type: "choice",
    act: 1, sceneNumber: 6,
    question: "Bagaimana kamu merespons?",
    characters: [{
      id: "rinn",
      sprite: "/Image/Rinn/eye-close-smile.png",
      position: "right",
      size: "large",
    }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.45)" },
    options: [
      { id: "c1_opt1", text: "Maaf, aku tidak ingat kamu.",          next: "act1_s7a", affection: { character: "rinn", amount: -5 } },
      { id: "c1_opt2", text: "Rinn... tentu aku ingat!",             next: "act1_s7b", affection: { character: "rinn", amount: 10 } },
      { id: "c1_opt3", text: "Ceritakan lebih banyak tentang kita.", next: "act1_s7c", affection: { character: "rinn", amount: 5  } },
    ],
  },
  {
    id: "act1_s7a",
    type: "dialogue",
    act: 1, sceneNumber: 7,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "...Ah. Begitu ya.\n\nGak apa-apa. Mungkin memang sudah terlalu lama.",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large" }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act1_s8",
  },
  {
    id: "act1_s7b",
    type: "dialogue",
    act: 1, sceneNumber: 7,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "Beneran?! Yay~!\n\nAku khawatir kamu sudah melupakanku selamanya...",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large" }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act1_s8",
  },
  {
    id: "act1_s7c",
    type: "dialogue",
    act: 1, sceneNumber: 7,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "Hmm... Dari mana aku harus mulai?\n\nSemuanya berubah sejak hari itu. 4th November.",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large" }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act1_s8",
  },
  {
    id: "act1_s8",
    type: "dialogue",
    act: 1, sceneNumber: 8,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "Ngomong-ngomong... kamu mau kemana hari ini?\n\nKita kan janji mau pergi bareng.",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large" }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act1_end",
  },
  {
    id: "act1_end",
    type: "ending",
    act: 1, sceneNumber: 9,
    endingType: "act",
    title: "— Act 1 Selesai —",
    subtitle: "Kenangan pun mulai terungkap...",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    bg: { color: "#06020f" },
    audio: { bgmFade: true }, // ← fade out BGM gracefully at act end
    next: "act2_s1",
  },
];