import { Scene } from "@/types/game";

export const ACT_1_SCENES: Scene[] = [
  {
    id: "act1_s1",
    type: "transition",
    act: 1, sceneNumber: 1,
    narrationText: "4th November.\nPagi yang seperti biasa...",
    nextScene: "act1_s2",
    duration: 3200,
    backgroundColor: "#0a0618",
  },
  {
    id: "act1_s2",
    type: "monologue",
    act: 1, sceneNumber: 2,
    dialogueText: "Aku membuka mata.\n\nSemuanya terasa... biasa. Seperti hari-hari lainnya.",
    backgroundColor: "#ffffff",
    nextScene: "act1_s3",
  },
  {
    id: "act1_s3",
    type: "dialogue",
    act: 1, sceneNumber: 3,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "Ohayo~! Kamu akhirnya bangun juga.",
    backgroundColor: "#ffffff",
    nextScene: "act1_s4",
  },
  {
    id: "act1_s4",
    type: "monologue",
    act: 1, sceneNumber: 4,
    dialogueText: "Gadis itu berdiri di depanku, tersenyum seperti tidak ada yang aneh.\n\nTapi... siapa dia?",
    backgroundColor: "#ffffff",
    nextScene: "act1_s5",
  },
  {
    id: "act1_s5",
    type: "dialogue",
    act: 1, sceneNumber: 5,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "Aku Rinn. Masa kamu lupa? Kita sudah kenal sejak lama, lho.",
    backgroundColor: "#ffffff",
    nextScene: "act1_s6",
  },
  {
    id: "act1_s6",
    type: "choice",
    act: 1, sceneNumber: 6,
    questionText: "Bagaimana kamu merespons?",
    backgroundColor: "#ffffff",
    options: [
      {
        id: "c1_opt1",
        text: "Maaf, aku tidak ingat kamu.",
        nextScene: "act1_s7a",
        affection: { character: "rinn", amount: -5 },
      },
      {
        id: "c1_opt2",
        text: "Rinn... tentu aku ingat!",
        nextScene: "act1_s7b",
        affection: { character: "rinn", amount: 10 },
      },
      {
        id: "c1_opt3",
        text: "Ceritakan lebih banyak tentang kita.",
        nextScene: "act1_s7c",
        affection: { character: "rinn", amount: 5 },
      },
    ],
  },
  {
    id: "act1_s7a",
    type: "dialogue",
    act: 1, sceneNumber: 7,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "...Ah. Begitu ya.\n\nGak apa-apa. Mungkin memang sudah terlalu lama.",
    backgroundColor: "#ffffff",
    nextScene: "act1_s8",
  },
  {
    id: "act1_s7b",
    type: "dialogue",
    act: 1, sceneNumber: 7,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "Beneran?! Yay~!\n\nAku khawatir kamu sudah melupakanku selamanya...",
    backgroundColor: "#ffffff",
    nextScene: "act1_s8",
  },
  {
    id: "act1_s7c",
    type: "dialogue",
    act: 1, sceneNumber: 7,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "Hmm... Dari mana aku harus mulai?\n\nSemuanya berubah sejak hari itu. 4th November.",
    backgroundColor: "#ffffff",
    nextScene: "act1_s8",
  },
  {
    id: "act1_s8",
    type: "dialogue",
    act: 1, sceneNumber: 8,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "Ngomong-ngomong... kamu mau kemana hari ini?\n\nKita kan janji mau pergi bareng.",
    backgroundColor: "#ffffff",
    nextScene: "act1_end",
  },
  {
    id: "act1_end",
    type: "ending",
    act: 1, sceneNumber: 9,
    endingType: "act",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    endingText: "— Act 1 Selesai —",
    nextScene: "act2_s1", // continues to Act 2
  },
];
