// scripts/generateAssetList.js

const fs = require('fs');
const path = require('path');

const publicDir = path.join(process.cwd(), 'public');
const outputFile = path.join(process.cwd(), 'lib', 'assetList.ts');

const imageExts = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.svg'];
const audioExts = ['.mp3', '.wav', '.ogg', '.m4a'];

function getAllAssets(dir, baseDir = '') {
  let assets = [];
  const files = fs.readdirSync(dir);

  for (const file of files) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    const relativePath = path.join(baseDir, file).replace(/\\/g, '/');

    if (stat.isDirectory()) {
      assets = assets.concat(getAllAssets(fullPath, relativePath));
    } else {
      const ext = path.extname(file).toLowerCase();
      if (imageExts.includes(ext) || audioExts.includes(ext)) {
        assets.push(`'/${relativePath}'`);
      }
    }
  }

  return assets;
}

console.log('🔍 Scanning public folder...');
const assets = getAllAssets(publicDir);

const content = `// Auto-generated by scripts/generateAssetList.js
// DO NOT EDIT MANUALLY

export const ASSET_LIST = [
  ${assets.join(',\n  ')}
];

export const ASSET_COUNT = ${assets.length};
`;

fs.writeFileSync(outputFile, content);
console.log(`✅ Generated ${assets.length} assets to lib/assetList.ts`);