import { Scene } from "@/types/game";

export const ACT_2_SCENES: Scene[] = [
  {
    id: "act2_s1",
    type: "transition",
    act: 2, sceneNumber: 1,
    narrationText: "Beberapa jam kemudian...\nDi jalan menuju sekolah.",
    nextScene: "act2_s2",
    duration: 3000,
    backgroundColor: "#0a0618",
  },
  {
    id: "act2_s2",
    type: "monologue",
    act: 2, sceneNumber: 2,
    dialogueText: "Aku berjalan di sampingnya.\n\nAneh. Rasanya seperti pernah melewati jalan ini bersamanya... tapi kapan?",
    backgroundColor: "#ffffff",
    nextScene: "act2_s3",
  },
  {
    id: "act2_s3",
    type: "dialogue",
    act: 2, sceneNumber: 3,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "Hei, kamu kenapa diam terus?\n\nAda yang dipikirin?",
    backgroundColor: "#ffffff",
    nextScene: "act2_s4",
  },
  {
    id: "act2_s4",
    type: "choice",
    act: 2, sceneNumber: 4,
    questionText: "Kamu menjawab...",
    backgroundColor: "#ffffff",
    options: [
      {
        id: "c2_opt1",
        text: "Gak ada, cuma ngantuk aja.",
        nextScene: "act2_s5a",
        affection: { character: "rinn", amount: 0 },
      },
      {
        id: "c2_opt2",
        text: "Aku mikirin kamu, sebenarnya.",
        nextScene: "act2_s5b",
        affection: { character: "rinn", amount: 15 },
      },
    ],
  },
  {
    id: "act2_s5a",
    type: "dialogue",
    act: 2, sceneNumber: 5,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "Hahaha, makanya tidur yang bener!\n\nAyo, nanti terlambat.",
    backgroundColor: "#ffffff",
    nextScene: "act2_s6",
  },
  {
    id: "act2_s5b",
    type: "dialogue",
    act: 2, sceneNumber: 5,
    character: "Rinn",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    dialogueText: "E-eh?!\n\n...\n\nJangan bilang hal aneh-aneh gitu dong!",
    backgroundColor: "#ffffff",
    nextScene: "act2_s6",
  },
  {
    id: "act2_s6",
    type: "monologue",
    act: 2, sceneNumber: 6,
    dialogueText: "Dia berjalan lebih cepat, sedikit menjauh.\n\nTapi aku bisa melihat telinganya memerah.",
    backgroundColor: "#ffffff",
    nextScene: "act2_end",
  },
  {
    id: "act2_end",
    type: "ending",
    act: 2, sceneNumber: 7,
    endingType: "act",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    endingText: "— Act 2 Selesai —",
    nextScene: undefined, // end of available content
  },
];
