import { Scene } from "@/types/game";

export const ACT_2_SCENES: Scene[] = [
  {
    id: "act2_s1",
    type: "transition",
    act: 2, sceneNumber: 1,
    text: "Beberapa jam kemudian...\nDi jalan menuju sekolah.",
    bg: { color: "#06020f" },
    duration: 3000,
    next: "act2_s2",
  },
  {
    id: "act2_s2",
    type: "monologue",
    act: 2, sceneNumber: 2,
    text: "Aku berjalan di sampingnya.\n\nAneh. Rasanya seperti pernah melewati jalan ini bersamanya... tapi kapan?",
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act2_s3",
  },
  {
    id: "act2_s3",
    type: "dialogue",
    act: 2, sceneNumber: 3,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "Hei, kamu kenapa diam terus?\n\nAda yang dipikirin?",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large" }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act2_s4",
  },
  {
    id: "act2_s4",
    type: "choice",
    act: 2, sceneNumber: 4,
    question: "Kamu menjawab...",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large" }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.45)" },
    options: [
      { id: "c2_opt1", text: "Gak ada, cuma ngantuk aja.",          next: "act2_s5a", affection: { character: "rinn", amount: 0  } },
      { id: "c2_opt2", text: "Aku mikirin kamu, sebenarnya.",        next: "act2_s5b", affection: { character: "rinn", amount: 15 } },
    ],
  },
  {
    id: "act2_s5a",
    type: "dialogue",
    act: 2, sceneNumber: 5,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "Hahaha, makanya tidur yang bener!\n\nAyo, nanti terlambat.",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large" }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act2_s6",
  },
  {
    id: "act2_s5b",
    type: "dialogue",
    act: 2, sceneNumber: 5,
    speaker: "Rinn",
    speakerId: "rinn",
    text: "E-eh?!\n\n...\n\nJangan bilang hal aneh-aneh gitu dong!",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large" }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act2_s6",
  },
  {
    id: "act2_s6",
    type: "monologue",
    act: 2, sceneNumber: 6,
    text: "Dia berjalan lebih cepat, sedikit menjauh.\n\nTapi aku bisa melihat telinganya memerah.",
    characters: [{ id: "rinn", sprite: "/Image/Rinn/eye-close-smile.png", position: "right", size: "large", dim: true }],
    bg: { image: "/Image/GameBG/Bg-1.jpg", overlay: "rgba(0,0,0,0.15)" },
    next: "act2_end",
  },
  {
    id: "act2_end",
    type: "ending",
    act: 2, sceneNumber: 7,
    endingType: "act",
    title: "— Act 2 Selesai —",
    subtitle: "Perjalanan masih panjang...",
    characterSprite: "/Image/Rinn/eye-close-smile.png",
    bg: { color: "#06020f" },
    next: undefined,
  },
];